appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YXHRkL8DjB99CG2Q3fIOxtA5wq0meR+A4l0u+oqA5sHlMqHASmYey8WHJrMH9tx7uT8fhQtJoOe/AoVmbMV1FUCQQa3BFr0O43zPN+5xTomKG4JN8RRJCRXtqCO9V/R89tRzCcNCXokWx6hVtU8GCdVvD/8t3PZ0HU8KXITQlOm+0RcZoeUwfiPP6EjqLbZZs2NGF9PvGh7njqB9N2swXt57BSaDLmmA5o/E9jS61n4kl6L43SQzKFoZvS28CmDkiIhFhDu3JzyG6EbkbTXR0XvTx9nOwOniqVkmzattPTN2R1TEGAynUK/46pczlmCBihst7vosb5+DHDbarT0O72JSOmoiGq4M0W8QKLfv3B1rw5EimkCCvEr2FEOmYwXuPNvNFnQZBA8K/aUvIRmRAlj6MPa2agXdm5HxVUYXZ9fZ3kj3sSli/UwIr/XPpPCFZDIdp8nZ43/6QTt1hJNOTvNz38EaFQRcyxJrgn9Fg2LxbyFE7PsF3t5cVPUvaldU1+691dwQ6mn9i4FgvTtpjocIXktEabte9mUl/XKOPmrhe4FEPO6m1+ZjJQE85T/GwUAaToZenHhX42iTRM7yukJ5P1+A+RaBA7fADskYkjwg+bdSeaFs91lvZ4bllC24V2Cr36xTlFg9GmweuX+90qWlRZO16O0QtbN4/AvJZ8o=}
